-- Create Events Table
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null, -- Keeping as text for simplicity to match UI, or use date/timestamp
  time text not null,
  location text not null,
  category text not null,
  image_url text, -- CSS class or URL
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Certificates Table
create table public.certificates (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  issuer text not null,
  date_issued text not null,
  certificate_code text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Registrations Table
create table public.registrations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  event_id bigint references public.events not null,
  status text default 'Registered',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, event_id)
);

-- Enable RLS
alter table public.events enable row level security;
alter table public.certificates enable row level security;
alter table public.registrations enable row level security;

-- Policies
-- Events: Everyone can read, only admins (service role) can insert/update (for now, or authenticated users if we want community events)
create policy "Public events are viewable by everyone" on public.events for select using (true);

-- Certificates: Users can read their own
create policy "Users can view own certificates" on public.certificates for select using (auth.uid() = user_id);
-- Public verification policy (allow anyone to find by code - handled via RPC or careful select policy if needed, for now let's allow public read for verification if we query by ID?)
-- Actually for verification we might need a secure function or just allow public read of certificates if they have the code. 
-- Let's allow public read for simplicity in this demo, or restrict. 
-- For verification page: "select * from certificates where certificate_code = 'XYZ'"
create policy "Certificates are verifiable" on public.certificates for select using (true); 

-- Registrations: Users can read/create their own
create policy "Users can view own registrations" on public.registrations for select using (auth.uid() = user_id);
create policy "Users can register themselves" on public.registrations for insert with check (auth.uid() = user_id);

-- Insert Mock Data for Events
insert into public.events (title, date, time, location, category, image_url, description) values
('AI & Machine Learning Workshop', 'Nov 28, 2025', '10:00 AM - 2:00 PM', 'Tech Hub, Room 301', 'Technical', 'bg-primary/20', 'Dive deep into neural networks and build your first ML model.'),
('Web Development Bootcamp', 'Dec 05, 2025', '9:00 AM - 5:00 PM', 'Virtual (Zoom)', 'Technical', 'bg-secondary/20', 'Full stack development crash course.'),
('Public Speaking Masterclass', 'Oct 20, 2025', '3:00 PM - 5:00 PM', 'Auditorium B', 'Soft Skills', 'bg-accent/20', 'Overcome stage fright and deliver impactful presentations.');
